### ISSUE TITLE
Allow for a gallery of cards with no images

### ISSUE THREAD

**Issue by christinach** [pulibrary/lux#166]
Currently defaults to icon representing missing image (unknown file)
![Screen Shot 2019-05-21 at 4 57 53 PM](https://user-images.githubusercontent.com/9905193/58130250-993cb600-7be9-11e9-9b9e-c6c74904c8b5.png)

**Comment by sdellis** [comment]
This is a Gallery issue.

**Comment by axamei** [comment]
@christinach We added a [GridItem](https://pulibrary.github.io/lux/docs/#/Elements/GridItem) recently. This new component adds the ability to layout items on the page. If you combine this with the card element, you should be able accomplish the desired pattern. Please let me know if you would like to pair on this.

**Comment by christinach** [comment]
@axamei @sdellis thank you! I'll test it and let you know

**Comment by sdellis** [comment]
@christinach closing this for now. Feel free to reopen if it doesn't solve your problem.
