### ISSUE TITLE
Date Chooser

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lux#168]
Create a Date selector

**Comment by axamei** [comment]
Requirements:
  * label
  * input (text) with defined regex pattern for validation of date format mm/dd/yyyy
    * user should be able to type in date and should not be forced to use calendar picker
  * calendar icon 
  * calendar picker activated on click

**Comment by sdellis** [comment]
Looks like this is a good option: https://github.com/nathanreyes/v-calendar

**Comment by axamei** [comment]
@sdellis #178 has the single mode option. We might want to add variants to handle date range and date time inputs.

**Comment by sdellis** [comment]
I'm adding the date range option in the `datepicker-range` branch.

**Comment by hackmastera** [comment]
When I try to enter a date in the specified format directly into the text box it goes super wonky. This is just on the lux documentation site.
