### ISSUE TITLE
Alerts - the display of alerts is inconsistent and buggy

### ISSUE THREAD

**Issue by axamei** [pulibrary/lux#2]
This will be our first component to standardize. Depending on the app/site alerts are marked up and styled in an inconsistent way. Let's include resources pointing to research/best practices on presenting alerts in this thread.

**Comment by sdellis** [comment]
Here's an example of how OL, Figgy, and Figgy Filemanager do alerts differently, even though all use Bootstrap and are alerting the user to "success" in a task: 

OrangeLight:
<img width="1207" alt="screen shot 2018-03-07 at 11 12 21 am" src="https://user-images.githubusercontent.com/609368/37103599-97fb5130-21f8-11e8-8bde-bcb99c67bd20.png">

Figgy:
<img width="1438" alt="screen shot 2018-03-07 at 11 22 06 am" src="https://user-images.githubusercontent.com/609368/37104196-14422934-21fa-11e8-9d13-3fff33a976bd.png">

Filemanager:
<img width="838" alt="screen shot 2018-03-07 at 11 23 09 am" src="https://user-images.githubusercontent.com/609368/37104206-1d33e7bc-21fa-11e8-8a6d-c773a3f26b17.png">

Also, the screenshots don't show animations that occur in OL and Filemanager that draw the eye to the alert.

**Comment by sdellis** [comment]
Also, [this user messaging writing guide](https://material.io/guidelines/style/writing.html) may be somewhat relevant here, though it's more about writing style in messaging than design style or markup.

**Comment by axamei** [comment]
@sdellis the writing style guide is on point. I think our components should have clear and consistent language. I think we can scope it to the component level so that it is relevant to this documentation/guide.

**Comment by axamei** [comment]
Weather alert on the main library site:
<img width="1212" alt="screen shot 2018-03-07 at 11 35 38 am" src="https://user-images.githubusercontent.com/8161144/37105343-e62e2900-21fc-11e8-800f-9743511a2596.png">

Having all text bold is bad. And, there is a double underline for links.

**Comment by sdellis** [comment]
The above alert is interesting also because it doesn't have any way to dismiss it. If you're using the site remotely, you may not care about the weather. 

Here's a good "best practices" article on various types of alerts, although it calls them "Indicators, Validations, and Notifications": https://www.nngroup.com/articles/indicators-validations-notifications/

**Comment by axamei** [comment]
Here's another good resource for notifications/alerts "best practices": https://inclusive-components.design/notifications/ 

Let's come up with some criteria for alerts (maybe a markdown file in the repo itself is a better spot for this and we can begin the documentation process with this. what do you think @sdellis ?):

- [ ] All alert containers should have `role="status" aria-live="polite"`

**Comment by axamei** [comment]
Upon further research, I think this falls under the broader scope Communication / Messaging. There are different messages we want to communicate to our users and because of that there will be different components to represent the different types of messages. I think we've identified the Banner (system-wide alert/notification) and Toast (task/context-based, dismissable alert/notification). 

Do we use modals for messaging/communication on any of our apps? If so, that should also be included under this.

**Comment by sdellis** [comment]
👍 Yes, I'm on board with this direction. 

As for modals, in Figgy, we have the "Browse Everything" modal for selecting images to upload. I also intend to create a "You have unsaved changes. Are you sure you want to leave this page without saving?" dialog in the Filemanager.

Finding aids uses a modal for the "Request confirmation" piece, as well as the "Suggest a Correction" and inline help. I'm not wedded to any of that, but I think Finding Aids as a whole is a different animal at this point. 

Of that list, the only one that probably _should_ be a modal is the Filemanager dialog.

## Modals (for interrupting flow to obtain user decision, acknowledgement, or input)
- [ ] All Modal containers should have `role="dialog" aria-modal="true" aria-labelledby="idOfLabelElement" aria-describedby="idOfDescriptionElement"` ([See MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role))

There is also the new `aria-modal` property. ([See W3C spec](https://www.w3.org/TR/wai-aria-1.1/#aria-modal))

**Comment by axamei** [comment]
Adding tooltips to the list... 
<img width="217" alt="screen shot 2018-03-28 at 3 03 51 pm" src="https://user-images.githubusercontent.com/8161144/38050513-47735936-3299-11e8-92d5-579c1c1a1553.png">
