### ISSUE TITLE
Allow for dataTables to have checkboxes in first or last columns

### ISSUE THREAD

**Issue by axamei** [pulibrary/lux#283]
We want to be able to able to put inputs (like checkboxes) in tables.

**Comment by sdellis** [comment]
I'm thinking about this a bit more and slots will really reduce the control we have over the way dataTables are used -- I'm not sure we want to go there just to add a checkbox in a row. 

I think a checkbox for a row is a common use case for doing bulk operations, so  perhaps we simply want to allow for one of the fields (like `id`) to have a `checkbox=true` attribute and it's value gets used for the value of the input. This would be a simpler solution than opening dataTables up to include arbitrary markup that may not be written in the most Accessible way. 

@axamei what do you think?

**Comment by axamei** [comment]
Sounds good. Do we want to limit the checkbox to only appear on the first/last columns?
