### ISSUE TITLE
Discuss and determine format for documentation of UI components

### ISSUE THREAD

**Issue by axamei** [pulibrary/lux#3]
What is our plan in documenting UI components? How do we want this documentation formatted? What information should it include? A good read to start the conversation: https://medium.com/eightshapes-llc/documenting-components-9fe59b80c015

**Comment by sdellis** [comment]
That is an excellent article series @axamei! Thanks for sharing.

I think we need to see if @kevinreiss can give us some dedicated time to collaborate on this as an official project. Can we prioritize this? We also need to get buy-in and feedback from the other developers, especially if we intend to replace (or somehow integrate with) Bootstrap.

**Comment by sdellis** [comment]
I'm going to drop these in here so we don't lose them for further reading/discussion:

https://vueds.com/

https://github.com/viljamis/vue-design-system/wiki

https://viljamis.com/2018/vue-design-system/

**Comment by axamei** [comment]
All component descriptions should include “…and what I do is…” to clearly define use case
