### ISSUE TITLE
Allow DataTable row values to have links

### ISSUE THREAD

**Issue by sdellis** [pulibrary/lux#301]
To add links to values, perhaps we structure a row like this?
```
{
	'id': 1,
	'name': {value:  'abc', link: 'https://abc.com', row-link: true},
	'email': {value:  'someone@example.com', link: 'mailto:someone@example.com'}, 
	'age': 42 
}
```
In order to 1) allow for the convenience of not having to provide a null link for every data value, and 2) avoid a breaking change, we will have to map all property values into objects with value and link properties using the `created` lifecycle hook. (I'm not sure what the performance ramifications are for large datasets.) The row should be linkable through the `row-link` boolean property.

**Comment by axamei** [comment]
Closed by #303
