### ISSUE TITLE
Date Picker does not allow users to remove a value

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/lux#404]
When using the date picker with a default-date to pass an existing date value, users can not remove the date string to save a nil value. Can be replicated in the lux documentation page: https://pulibrary.github.io/lux/docs/#/Elements/LuxDatePicker

**Comment by eliotjordan** [comment]
I'm working on embargo dates in Figgy. I'm using the default-date property to populate an existing value. Users should be able to delete the value from the input.

**Comment by hackartisan** [comment]
fixed in #406
